singleServerConfig:
  address: "redis://127.0.0.1:6379"
  password: null
  database: 0
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  subscriptionsPerConnection: 5
  clientName: null
#  集群模式
#  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
#  slaveSubscriptionConnectionMinimumIdleSize: 1
#  slaveSubscriptionConnectionPoolSize: 50
#  slaveConnectionMinimumIdleSize: 32
#  slaveConnectionPoolSize: 64
#  masterConnectionMinimumIdleSize: 32
#  masterConnectionPoolSize: 64
#  readMode: "SLAVE"
#  sentinelAddresses:
#    - "redis://127.0.0.1:26379"
#    - "redis://127.0.0.1:26389"
#  masterName: "mymaster"
threads: 0
nettyThreads: 0
#codec: !<org.redisson.client.codec.StringCodec> {}
codec: !<org.redisson.codec.JsonJacksonCodec> {}
"transportMode": "NIO"